# Generated by Django 4.0.4 on 2022-07-08 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32, unique=True, verbose_name='아이디')),
                ('password1', models.CharField(max_length=128, verbose_name='비밀번호')),
                ('nickname', models.CharField(max_length=16, unique=True, verbose_name='닉네임')),
                ('email', models.EmailField(max_length=128, unique=True, verbose_name='이메일')),
            ],
        ),
    ]
